# -*- mode: ruby -*-
# vi: set ft=ruby :
# default username:
# vagrant:vagrant
# root:vagrant

COUNT = 3
BOX_NAME = "bento/centos-7.9"
# BOX_NAME = "ubuntu/bionic64"

Vagrant.configure("2") do |config|
  (1..COUNT).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = BOX_NAME
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network "private_network", ip: "172.42.42.10#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 4096
        v.cpus = 4
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
    end
  end
end