--- 
- name: Install keepalived
  apt:
    name: keepalived
    state: present

- name: Enable keepalived
  systemd:
    name: keepalived
    enabled: yes

- name: Config keepalived
  copy:
    dest: /etc/keepalived/check_apiserver.sh
    mode: 0777
    content: |
      #!/bin/sh
      errorExit() {
        echo "*** $@" 1>&2
        exit 1
      }

      curl --silent --max-time 2 --insecure https://localhost:6443/ -o /dev/null || errorExit "Error GET https://localhost:6443/"
      if ip addr | grep -q 172.16.16.100; then
        curl --silent --max-time 2 --insecure https://172.16.16.100:6443/ -o /dev/null || errorExit "Error GET https://172.16.16.100:6443/"
      fi

- name: Config keepalived
  copy:
    dest: /etc/keepalived/keepalived.conf
    content: |
      vrrp_script check_apiserver {
        script "/etc/keepalived/check_apiserver.sh"
        interval 3
        timeout 10
        fall 5
        rise 2
        weight -2
      }

      vrrp_instance VI_1 {
          state BACKUP
          interface eth1
          virtual_router_id 1
          priority 100
          advert_int 5
          authentication {
              auth_type PASS
              auth_pass mysecret
          }
          virtual_ipaddress {
              172.16.16.100
          }
          track_script {
              check_apiserver
          }
      }

- name: Restart keepalived
  service:
    name: keepalived
    state: restarted      