---
- name: Initialize the Kubernetes cluster using kubeadm
  become: yes
  shell: |
    kubeadm reset -f
    kubeadm init \
      --apiserver-advertise-address="192.168.0.126" \
      --apiserver-cert-extra-sans="192.168.0.126"  \
      --node-name k8s-master \ 
      --pod-network-cidr=192.168.0.0/16 \
      --image-repository registry.aliyuncs.com/google_containers \
      --kubernetes-version v1.19.0

- name: Setup kubeconfig for ubuntu user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/ubuntu/.kube
    - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    - chown ubuntu:ubuntu /home/ubuntu/.kube/config