apiVersion: v1
kind: Namespace
metadata:
  name: test-persistence-ns

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-volumeM
  namespace: test-persistence-ns
spec: 
  containers: 
  - name: tomcat
    image: tomcat
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: app-logs
      mountPath: /usr/local/tomcat/logs
  - name: busybox
    image: busybox
    command: ["sh", "-c", "tail -f /logs/catalina*.log"]
    volumeMounts:
    - name: app-logs
      mountPath: /logs
  volumes:
  - name: app-logs
    emptyDir: {}