---
- name: Update to using aliyun source
  copy: 
    dest: /etc/apt/sources.list
    content: |
      deb http://mirrors.aliyun.com/ubuntu focal main restricted
      deb http://mirrors.aliyun.com/ubuntu focal-updates main restricted
      deb http://mirrors.aliyun.com/ubuntu focal universe
      deb http://mirrors.aliyun.com/ubuntu focal-updates universe
      deb http://mirrors.aliyun.com/ubuntu focal multiverse
      deb http://mirrors.aliyun.com/ubuntu focal-updates multiverse
      deb http://mirrors.aliyun.com/ubuntu focal-backports main restricted universe multiverse
      deb http://mirrors.aliyun.com/ubuntu focal-security main restricted
      deb http://mirrors.aliyun.com/ubuntu focal-security universe
      deb http://mirrors.aliyun.com/ubuntu focal-security multiverse    

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap

- name: Disable swap
  command: swapoff -a

- name: Disable fireware
  command: systemctl disable --now ufw

- name: Install Dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Set time zone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai

- name: Install ntp
  apt:
    name: ntp
    state: present
    update_cache: yes
