---
# tasks file for master
- name: Initialize the Kubernetes cluster using kubeadm
  shell: |
    kubeadm init \
      --apiserver-advertise-address="172.42.42.101" \
      --apiserver-cert-extra-sans="172.42.42.101"  \
      --image-repository registry.aliyuncs.com/google_containers \
      --node-name k8s-master \
      --pod-network-cidr=10.244.0.0/16 \
      --ignore-preflight-errors=SystemVerification \
      --kubernetes-version 1.20.0

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Install flannel pod network
  become: false
  command: kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
