# Add slave to cluster
- name: Generate worker join command
  become: no
  hosts:
    - master
  tasks:
    - name: Generate certificate key
      command: kubeadm certs certificate-key
      register: certificate_key

    - name: Upload certificate key
      command: kubeadm init phase upload-certs --upload-certs --certificate-key="{{ certificate_key.stdout_lines[0] }}"

    - name: generate master join command
      command: kubeadm token create --print-join-command --certificate-key "{{ certificate_key.stdout_lines[0] }}"
      register: join_command

    - name: Copy join command to master slave node
      copy:
        content: "{{ join_command.stdout_lines[0] }} --apiserver-advertise-address={{ host }} "
        dest: "/tmp/master-join-command.sh"
        mode: 0777
      delegate_to: "{{ host }}"
      with_items: "{{ groups['slave'] }}"
      loop_control:
        loop_var: host

- name: Join the master node to cluster
  become: yes
  hosts:
    - slave
  tasks:
    - name: execute join command
      command: sh /tmp/master-join-command.sh
