---
- hosts: all
  tasks:
  - name: Update and upgrade apt packages
    become: true
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://repo.huaweicloud.com/docker-ce/linux/ubuntu/gpg
      state: present

  - name: Adding apt repository for Docker
    apt_repository:
      repo: deb [arch=amd64] https://repo.huaweicloud.com/docker-ce/linux/ubuntu bionic stable
      state: present
      filename: docker.ce.list    

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0    

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted  