---
- name: Install Kubernates
  hosts: all
  become: yes
  roles:
    - common
    - docker
    - kubernetes/install

- name: Initalize Kubernetes master server
  hosts: master
  become: yes
  roles:
    - kubernetes/master

- name: Generate join command
  hosts: master
  tasks:
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: worker_join_command

    - name: Copy join command to local file
      local_action: copy content="{{ worker_join_command.stdout_lines[0] }}" dest="/tmp/worker-join-command"

- name: Join to cluster
  hosts: worker
  tasks:
    - name: Copy the join command to server location
      copy:
        src: /tmp/worker-join-command
        dest: /tmp/worker-join-command.sh
        mode: 0777

    - name: Join the node to cluster
      command: sh /tmp/worker-join-command.sh
