apiVersion: v1
kind: Pod
metadata:
  name: vol-nfs-pod
  labels:
    app: redis
spec: 
  containers:
  - name: redis
    image: redis:4-alpine
    ports: 
    - containerPort: 6379
      name: redisport
    volumeMounts:
    - mountPath: /data
      name: redisdata
  volumes:
  - name: redisdata
    nfs:
      server: 192.168.153.144
      path: /data/
      readOnly: false