---
- name: Adding apt repository for Docker
  apt_repository:
    repo: deb [arch=amd64] https://repo.huaweicloud.com/docker-ce/linux/ubuntu bionic stable
    state: present
    filename: docker.ce.list

- name: Install docker and its dependecies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - docker status
