---
- name: Install haproxy
  apt:
    name: haproxy
    state: present

- name: Enable haproxy
  systemd:
    name: haproxy
    enabled: yes

- name: Config haproxy
  copy:
    dest: /etc/haproxy/haproxy.cfg
    content: |
      frontend stats
        bind *:8404
        mode http
        stats enable
        stats hide-version
        stats realm Haproxy\ Statistics
        stats uri /haproxy?stats
      
      frontend kubernetes-frontend
        bind *:6443
        mode tcp
        option tcplog
        default_backend kubernetes-backend

      backend kubernetes-backend
        option httpchk GET /healthz
        http-check expect status 200
        mode tcp
        option ssl-hello-chk
        balance roundrobin
          server kmaster1 172.16.16.101:6443 check fall 3 rise 2
          server kmaster2 172.16.16.102:6443 check fall 3 rise 2
          server kmaster3 172.16.16.103:6443 check fall 3 rise 2

- name: Restart service haproxy
  service:
    name: haproxy
    state: restarted          