kind: Service
apiVersion: v1
metadata:
  name: zoo1-svc
  namespace: kafka
  labels:
    app: zookeeper
    node: node1
spec:
  type: ClusterIP
  ports:
  - name: port-2181
    port: 2181
  - name: port-2888
    port: 2888
  - name: port-3888
    port: 3888
  selector:
    app: zookeeper
    node: node1

---
kind: Service
apiVersion: v1
metadata:
  name: zoo2-svc
  namespace: kafka
  labels:
    app: zookeeper
    node: node2
spec:
  type: ClusterIP
  ports:
  - name: port-2181
    port: 2181
  - name: port-2888
    port: 2888
  - name: port-3888
    port: 3888
  selector:
    app: zookeeper
    node: node2

---
kind: Service
apiVersion: v1
metadata:
  name: zoo3-svc
  namespace: kafka
  labels:
    app: zookeeper
    node: node3
spec:
  type: ClusterIP
  ports:
  - name: port-2181
    port: 2181
  - name: port-2888
    port: 2888
  - name: port-3888
    port: 3888
  selector:
    app: zookeeper
    node: node3
