# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_NO_PARALLEL'] = 'yes'
BOX_NAME = "ubuntu/bionic64"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
  ANSIBLE_RAW_SSH_ARGS = []

  (1..NODE_COUNT).each do |i|
    ANSIBLE_RAW_SSH_ARGS << "-o IdentityFile=.vagrant/machines/" + "node#{i}" + "/virtualbox/private_key"
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.box = BOX_NAME
      node.vm.box_check_update = false
      node.vm.network :private_network, ip: "192.168.33.#{i + 1}"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "node#{i}"
        vb.memory = 2560
        vb.cpus = 2
      end
    end
  end

  config.vm.define "ansible" do |node|
    node.vm.hostname = "ansible"
    node.vm.box = BOX_NAME
    node.vm.box_check_update = false
    node.vm.provider "virtualbox" do |vb|
        vb.name = "ansible"
        vb.memory = 2560
        vb.cpus = 2
    end
    node.vm.provision "ansible" do |ansible|
        ansible.raw_ssh_args = ANSIBLE_RAW_SSH_ARGS
        ansible.limit = "all"
        ansible.inventory_path = "ansible/hosts"
        ansible.playbook = "ansible/playbook.yml"
    end
  end
end