---
# tasks file for worker
- name: Copy the join command to server location
  copy: 
    src: /tmp/worker-join-command
    dest: /tmp/worker-join-command.sh 
    mode: 0777

- name: Join the node to cluster
  command: sh /tmp/worker-join-command.sh