---
# tasks file for worker
- name: pull required docker images
  shell: |
    docker pull public.ecr.aws/eks-distro/kubernetes/pause:v1.19.8-eks-1-19-4
    docker tag public.ecr.aws/eks-distro/kubernetes/pause:v1.19.8-eks-1-19-4 public.ecr.aws/eks-distro/kubernetes/pause:3.2

- name: Copy the join command to server location
  copy: 
    src: join-command 
    dest: /tmp/join-command.sh 
    mode: 0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh