---
- name: Add aliyun kubernetes apt key
  apt_key:
    url: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet=1.20.0-00
      - kubeadm=1.20.0-00
      - kubectl=1.20.0-00

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
