---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://repo.huaweicloud.com/docker-ce/linux/ubuntu/gpg
    state: present

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
    state: present
