---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swapfile from /etc/fstab
  shell: |
    sudo rm /swapfile
    #back up /etc/fstab:
    sudo cp /etc/fstab /etc/fstab.bak
    sudo sed -i '/\/swapfile/d' /etc/fstab

- name: Install Dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - software-properties-common

- name: Set time zone to Asia/Shanghai
  command: timedatectl set-timezone Asia/Shanghai
 
# sudo apt-get install ntp
- name: Install ntp
  apt:
    name: ntp
    state: present
    update_cache: yes
